services:
  auth.provider.oauth.service.vgindex:
    class: vgindex\oidc\service\vgindex
    arguments:
      - '@config'
      - '@request'
    tags:
      - { name: auth.provider.oauth.service }

  vgindex.oidc.listener:
    class: vgindex\oidc\event\listener
    arguments:
      - '@dbal.conn'
      - '@config'
      - '@passwords.manager'
      - '@user'
      - '%tables.users%'
      - '%tables.auth_provider_oauth_account_assoc%'
    tags:
      - { name: event.listener }
