-- Media types
INSERT INTO media_types (name, display_order) VALUES
    ('CD', 1),
    ('GD-ROM', 2),
    ('DVD-5', 3),
    ('DVD-9', 4),
    ('HD DVD (SL)', 5),
    ('HD DVD (DL)', 6),
    ('BD-25', 7),
    ('BD-50', 8),
    ('BD-66', 9),
    ('BD-100', 10),
    ('UMD (SL)', 11),
    ('UMD (DL)', 12),
    ('Nintendo GameCube Game Disc', 13),
    ('Wii Optical Disc (SL)', 14),
    ('Wii Optical Disc (DL)', 15),
    ('Wii U Optical Disc (SL)', 16);

-- Categories
INSERT INTO categories (name, display_order) VALUES
    ('Games', 1),
    ('Demos', 2),
    ('Coverdiscs', 3),
    ('Bonus Discs', 4),
    ('Applications', 5),
    ('Multimedia', 6),
    ('Add-Ons', 7),
    ('Educational', 8),
    ('Preproduction', 9),
    ('Video', 10),
    ('Audio', 11);

-- Regions (dat priority order first, then alphabetical)
INSERT INTO regions (name, flag_code, display_order) VALUES
    ('USA', 'us', 1),
    ('Japan', 'jp', 2),
    ('Europe', 'eu', 3),
    ('Asia', 'un', 4),
    ('UK', 'gb', 5),
    ('France', 'fr', 6),
    ('Spain', 'es', 7),
    ('Argentina', 'ar', 8),
    ('Australia', 'au', 9),
    ('Austria', 'at', 10),
    ('Belarus', 'by', 11),
    ('Belgium', 'be', 12),
    ('Brazil', 'br', 13),
    ('Bulgaria', 'bg', 14),
    ('Canada', 'ca', 15),
    ('China', 'cn', 16),
    ('Croatia', 'hr', 17),
    ('Czech', 'cz', 18),
    ('Denmark', 'dk', 19),
    ('Estonia', 'ee', 20),
    ('Export', 'un', 21),
    ('Finland', 'fi', 22),
    ('Germany', 'de', 23),
    ('Greece', 'gr', 24),
    ('Hungary', 'hu', 25),
    ('Iceland', 'is', 26),
    ('India', 'in', 27),
    ('Ireland', 'ie', 28),
    ('Israel', 'il', 29),
    ('Italy', 'it', 30),
    ('Korea', 'kr', 31),
    ('Latin America', 'un', 32),
    ('Lithuania', 'lt', 33),
    ('Netherlands', 'nl', 34),
    ('New Zealand', 'nz', 35),
    ('Norway', 'no', 36),
    ('Poland', 'pl', 37),
    ('Portugal', 'pt', 38),
    ('Romania', 'ro', 39),
    ('Russia', 'ru', 40),
    ('Scandinavia', 'un', 41),
    ('Serbia', 'rs', 42),
    ('Singapore', 'sg', 43),
    ('Slovakia', 'sk', 44),
    ('South Africa', 'za', 45),
    ('Sweden', 'se', 46),
    ('Switzerland', 'ch', 47),
    ('Taiwan', 'tw', 48),
    ('Thailand', 'th', 49),
    ('Turkey', 'tr', 50),
    ('Ukraine', 'ua', 51),
    ('United Arab Emirates', 'ae', 52),
    ('World', 'un', 53);

-- Languages (IETF BCP 47 codes, ordered by dat filename priority)
INSERT INTO languages (code, name, flag_code, display_order) VALUES
    ('en', 'English', 'eng', 1),
    ('ja', 'Japanese', 'jap', 2),
    ('fr', 'French', 'fre', 3),
    ('de', 'German', 'ger', 4),
    ('es', 'Spanish', 'spa', 5),
    ('it', 'Italian', 'ita', 6),
    ('nl', 'Dutch', 'dut', 7),
    ('pt', 'Portuguese', 'por', 8),
    ('sv', 'Swedish', 'swe', 9),
    ('no', 'Norwegian', 'nor', 10),
    ('da', 'Danish', 'dan', 11),
    ('fi', 'Finnish', 'fin', 12),
    ('zh', 'Chinese', 'chi', 13),
    ('ko', 'Korean', 'kor', 14),
    ('pl', 'Polish', 'pol', 15),
    ('ru', 'Russian', 'rus', 16),
    ('uk', 'Ukrainian', 'ukr', 17),
    ('el', 'Greek', 'gre', 18),
    ('hr', 'Croatian', 'hrv', 19),
    ('cs', 'Czech', 'cze', 20),
    ('hu', 'Hungarian', 'hun', 21),
    ('sk', 'Slovak', 'slk', 22),
    ('sl', 'Slovenian', 'slv', 23),
    ('ar', 'Arabic', 'ara', 24),
    ('th', 'Thai', 'tha', 25),
    ('tr', 'Turkish', 'tur', 26),
    ('eu', 'Basque', 'baq', 27),
    ('ca', 'Catalan', 'cat', 28),
    ('gd', 'Gaelic', 'gla', 29),
    ('hi', 'Hindi', 'hin', 30),
    ('pa', 'Punjabi', 'pan', 31),
    ('ta', 'Tamil', 'tam', 32),
    ('he', 'Hebrew', 'heb', 33),
    ('af', 'Afrikaans', 'afr', 34),
    ('ro', 'Romanian', 'ron', 35),
    ('is', 'Icelandic', 'isl', 36),
    ('la', 'Latin', 'lat', 37),
    ('mk', 'Macedonian', 'mkd', 38),
    ('id', 'Indonesian', 'ind', 39),
    ('lt', 'Lithuanian', 'lit', 40),
    ('sr', 'Serbian', 'srp', 41),
    ('be', 'Belarusian', 'bel', 42),
    ('et', 'Estonian', 'est', 43),
    ('lv', 'Latvian', 'lav', 44),
    ('sq', 'Albanian', 'sqi', 45),
    ('hy', 'Armenian', 'hye', 46),
    ('vi', 'Vietnamese', 'vie', 47),
    ('bg', 'Bulgarian', 'bul', 48);

-- Title types
INSERT INTO title_types (name, display_order) VALUES
    ('Disc Title', 1),
    ('Disc Number', 2),
    ('Spine', 3),
    ('In-game', 4),
    ('Native', 5),
    ('Internal', 6),
    ('Disc Label', 7);

-- Serial types
INSERT INTO serial_types (name, display_order) VALUES
    ('Disc', 1),
    ('Case', 2),
    ('Internal', 3);

-- Systems: CD-based
INSERT INTO systems (short_code, full_name, allowed_media, has_date_field, has_sbi, has_pvd, has_edc_field, display_order) VALUES
    ('psx', 'Sony PlayStation', '{1}', true, true, true, true, 1),
    ('ps2', 'Sony PlayStation 2', '{1,3,4}', true, false, true, false, 2),
    ('ps3', 'Sony PlayStation 3', '{6,7}', false, false, false, false, 3),
    ('psp', 'Sony PlayStation Portable', '{10}', false, false, false, false, 4),
    ('ss', 'Sega Saturn', '{1}', true, false, false, false, 5),
    ('dc', 'Sega Dreamcast', '{2}', true, false, false, false, 6),
    ('scd', 'Sega Mega-CD / Sega CD', '{1}', false, false, false, false, 7),
    ('pce', 'NEC PC Engine CD / TurboGrafx-CD', '{1}', false, false, false, false, 8),
    ('gc', 'Nintendo GameCube', '{3}', false, false, false, false, 9),
    ('wii', 'Nintendo Wii', '{3,4}', false, false, false, false, 10),
    ('xbox', 'Microsoft Xbox', '{3,4}', false, false, false, false, 11),
    ('xbox360', 'Microsoft Xbox 360', '{3,4}', false, false, false, false, 12),
    ('3do', 'Panasonic 3DO Interactive Multiplayer', '{1}', false, false, false, false, 13),
    ('pc', 'IBM PC compatible', '{1,3,4}', false, false, true, false, 14),
    ('mac', 'Apple Macintosh', '{1,3,4}', false, false, false, false, 15),
    ('audio-cd', 'Audio CD', '{1}', false, false, false, false, 16),
    ('dvd-video', 'DVD-Video', '{3,4}', false, false, false, false, 17),
    ('playdia', 'Bandai Playdia', '{1}', false, false, false, false, 18),
    ('pippin', 'Bandai / Apple Pippin', '{1}', false, false, false, false, 19),
    ('acd', 'Commodore Amiga CD', '{1}', false, false, false, false, 20),
    ('cd32', 'Commodore Amiga CD32', '{1}', false, false, false, false, 21),
    ('cdtv', 'Commodore Amiga CDTV', '{1}', false, false, false, false, 22),
    ('dvdpg', 'DVDPG', '{3,4}', false, false, false, false, 23),
    ('fmt', 'Fujitsu FM Towns series', '{1}', false, false, false, false, 24),
    ('pc-98', 'NEC PC-98 series', '{1}', false, false, false, false, 25);

-- Systems: additional systems
INSERT INTO systems (short_code, full_name, allowed_media, has_date_field, has_sbi, has_pvd, has_edc_field, display_order) VALUES
    ('ps4', 'Sony PlayStation 4', '{6,7,8,9}', false, false, false, false, 26),
    ('ps5', 'Sony PlayStation 5', '{6,7,8,9}', false, false, false, false, 27),
    ('vita', 'Sony PlayStation Vita', '{1}', false, false, false, false, 28),
    ('wiiu', 'Nintendo Wii U', '{3,4,6}', false, false, false, false, 29),
    ('switch', 'Nintendo Switch', '{6}', false, false, false, false, 30),
    ('xone', 'Microsoft Xbox One', '{6,7}', false, false, false, false, 31),
    ('xsx', 'Microsoft Xbox Series X/S', '{6,7,9}', false, false, false, false, 32),
    ('hddvd', 'HD-DVD', '{5}', false, false, false, false, 33),
    ('bd-video', 'Blu-ray Video', '{6,7}', false, false, false, false, 34),
    ('cdi', 'Philips CD-i', '{1}', false, false, false, false, 35),
    ('neo-geo', 'SNK Neo Geo CD', '{1}', false, false, false, false, 36),
    ('pcfx', 'NEC PC-FX', '{1}', false, false, false, false, 37),
    ('tg16', 'NEC TurboGrafx-16 / PC Engine', '{1}', false, false, false, false, 38),
    ('vb', 'VCD', '{1}', false, false, false, false, 39),
    ('palm-os', 'Palm OS', '{1}', false, false, false, false, 40),
    ('photo-cd', 'Photo CD', '{1}', false, false, false, false, 41),
    ('nuon', 'VM Labs NUON', '{3}', false, false, false, false, 42),
    ('n64dd', 'Nintendo 64DD', '{1}', false, false, false, false, 43),
    ('atari-jag', 'Atari Jaguar CD', '{1}', false, false, false, false, 44),
    ('3ds', 'Nintendo 3DS', '{1}', false, false, false, false, 45),
    ('nds', 'Nintendo DS', '{1}', false, false, false, false, 46),
    ('wii-u', 'Nintendo Wii U', '{4,6}', false, false, false, false, 47),
    ('psx-bios', 'Sony PlayStation - BIOS Images', '{1}', false, false, false, false, 90),
    ('ps2-bios', 'Sony PlayStation 2 - BIOS Images', '{1}', false, false, false, false, 91),
    ('xbox-bios', 'Microsoft Xbox - BIOS Images', '{1}', false, false, false, false, 92);

-- OIDC clients seed (for phpBB and MediaWiki)
INSERT INTO oauth_clients (client_id, client_secret, redirect_uri, name) VALUES
    ('phpbb-client', 'change-this-secret-phpbb', 'http://localhost:8080/forum/ucp.php?mode=login', 'phpBB Forum'),
    ('mediawiki-client', 'change-this-secret-mediawiki', 'http://localhost:8080/wiki/Special:PluggableAuthLogin', 'MediaWiki');
