-- Media types
INSERT INTO media_types (code, name, sort_order) VALUES
    ('cd',       'CD', 1),
    ('gdrom',    'GD-ROM', 2),
    ('dvd5',     'DVD-5', 3),
    ('dvd5gc',   'Nintendo GameCube Game Disc', 4),
    ('dvd5wii',  'Wii Optical Disc (SL)', 5),
    ('dvd9',     'DVD-9', 6),
    ('dvd9wii',  'Wii Optical Disc (DL)', 7),
    ('hdvd15',   'HD DVD (SL)', 8),
    ('hdvd30',   'HD DVD (DL)', 9),
    ('bd25',     'BD-25', 10),
    ('bd25wiiu', 'Wii U Optical Disc (SL)', 11),
    ('bd50',     'BD-50', 12),
    ('bd66',     'BD-66', 13),
    ('bd100',    'BD-100', 14),
    ('umd1',     'UMD (SL)', 15),
    ('umd2',     'UMD (DL)', 16);

-- Categories
INSERT INTO categories (name, sort_order) VALUES
    ('Games', 1),
    ('Demos', 2),
    ('Coverdiscs', 3),
    ('Bonus Discs', 4),
    ('Applications', 5),
    ('Multimedia', 6),
    ('Add-Ons', 7),
    ('Educational', 8),
    ('Preproduction', 9),
    ('Video', 10),
    ('Audio', 11);

-- Regions (dat order priority entries first, then sorted by code)
-- code: ISO 3166-1 alpha-2 for countries, X* (user-assigned) for non-country entries
INSERT INTO regions (code, name, flag_code, sort_order) VALUES
    ('us', 'USA',                  'us', 1),
    ('jp', 'Japan',                'jp', 2),
    ('xe', 'Europe',               'eu', 3),
    ('xa', 'Asia',                 'un', 4),
    ('gb', 'UK',                   'gb', 5),
    ('fr', 'France',               'fr', 6),
    ('es', 'Spain',                'es', 7),
    ('ae', 'United Arab Emirates', 'ae', 8),
    ('ar', 'Argentina',            'ar', 9),
    ('at', 'Austria',              'at', 10),
    ('au', 'Australia',            'au', 11),
    ('be', 'Belgium',              'be', 12),
    ('bg', 'Bulgaria',             'bg', 13),
    ('br', 'Brazil',               'br', 14),
    ('by', 'Belarus',              'by', 15),
    ('ca', 'Canada',               'ca', 16),
    ('ch', 'Switzerland',          'ch', 17),
    ('cn', 'China',                'cn', 18),
    ('cz', 'Czech',                'cz', 19),
    ('de', 'Germany',              'de', 20),
    ('dk', 'Denmark',              'dk', 21),
    ('ee', 'Estonia',              'ee', 22),
    ('fi', 'Finland',              'fi', 23),
    ('gr', 'Greece',               'gr', 24),
    ('hr', 'Croatia',              'hr', 25),
    ('hu', 'Hungary',              'hu', 26),
    ('ie', 'Ireland',              'ie', 27),
    ('il', 'Israel',               'il', 28),
    ('in', 'India',                'in', 29),
    ('is', 'Iceland',              'is', 30),
    ('it', 'Italy',                'it', 31),
    ('kr', 'Korea',                'kr', 32),
    ('lt', 'Lithuania',            'lt', 33),
    ('nl', 'Netherlands',          'nl', 34),
    ('no', 'Norway',               'no', 35),
    ('nz', 'New Zealand',          'nz', 36),
    ('pl', 'Poland',               'pl', 37),
    ('pt', 'Portugal',             'pt', 38),
    ('ro', 'Romania',              'ro', 39),
    ('rs', 'Serbia',               'rs', 40),
    ('ru', 'Russia',               'ru', 41),
    ('se', 'Sweden',               'se', 42),
    ('sg', 'Singapore',            'sg', 43),
    ('sk', 'Slovakia',             'sk', 44),
    ('th', 'Thailand',             'th', 45),
    ('tr', 'Turkey',               'tr', 46),
    ('tw', 'Taiwan',               'tw', 47),
    ('ua', 'Ukraine',              'ua', 48),
    ('xl', 'Latin America',        'un', 49),
    ('xp', 'Export',               'un', 50),
    ('xs', 'Scandinavia',          'un', 51),
    ('xw', 'World',                'un', 52),
    ('za', 'South Africa',         'za', 53);

-- Languages (IETF BCP 47 codes, ordered by dat filename priority)
INSERT INTO languages (code, name, flag_code, sort_order) VALUES
    ('en', 'English', 'eng', 1),
    ('ja', 'Japanese', 'jap', 2),
    ('fr', 'French', 'fre', 3),
    ('de', 'German', 'ger', 4),
    ('es', 'Spanish', 'spa', 5),
    ('it', 'Italian', 'ita', 6),
    ('nl', 'Dutch', 'dut', 7),
    ('pt', 'Portuguese', 'por', 8),
    ('sv', 'Swedish', 'swe', 9),
    ('no', 'Norwegian', 'nor', 10),
    ('da', 'Danish', 'dan', 11),
    ('fi', 'Finnish', 'fin', 12),
    ('zh', 'Chinese', 'chi', 13),
    ('ko', 'Korean', 'kor', 14),
    ('pl', 'Polish', 'pol', 15),
    ('ru', 'Russian', 'rus', 16),
    ('uk', 'Ukrainian', 'ukr', 17),
    ('el', 'Greek', 'gre', 18),
    ('hr', 'Croatian', 'hrv', 19),
    ('cs', 'Czech', 'cze', 20),
    ('hu', 'Hungarian', 'hun', 21),
    ('sk', 'Slovak', 'slk', 22),
    ('sl', 'Slovenian', 'slv', 23),
    ('ar', 'Arabic', 'ara', 24),
    ('th', 'Thai', 'tha', 25),
    ('tr', 'Turkish', 'tur', 26),
    ('eu', 'Basque', 'baq', 27),
    ('ca', 'Catalan', 'cat', 28),
    ('gd', 'Gaelic', 'gla', 29),
    ('hi', 'Hindi', 'hin', 30),
    ('pa', 'Punjabi', 'pan', 31),
    ('ta', 'Tamil', 'tam', 32),
    ('he', 'Hebrew', 'heb', 33),
    ('af', 'Afrikaans', 'afr', 34),
    ('ro', 'Romanian', 'ron', 35),
    ('is', 'Icelandic', 'isl', 36),
    ('la', 'Latin', 'lat', 37),
    ('mk', 'Macedonian', 'mkd', 38),
    ('id', 'Indonesian', 'ind', 39),
    ('lt', 'Lithuanian', 'lit', 40),
    ('sr', 'Serbian', 'srp', 41),
    ('be', 'Belarusian', 'bel', 42),
    ('et', 'Estonian', 'est', 43),
    ('lv', 'Latvian', 'lav', 44),
    ('sq', 'Albanian', 'sqi', 45),
    ('hy', 'Armenian', 'hye', 46),
    ('vi', 'Vietnamese', 'vie', 47),
    ('bg', 'Bulgarian', 'bul', 48);

-- Systems: Redump `code`; sort_order = first scrape appearance (min disc_id). `ecd` vs `audio-cd` for PK.
-- has_* = OR over scraped discs: has_date_field=d_date, has_sbi=d_libcrypt|d_securom, has_pvd=d_pvd, has_edc_field=d_edc (non-empty).
INSERT INTO systems (code, full_name, allowed_media, has_date_field, has_sbi, has_pvd, has_edc_field, sort_order) VALUES
    ('psx', 'Sony PlayStation', '{cd}', true, true, true, true, 1),
    ('ps2', 'Sony PlayStation 2', '{cd,dvd5,dvd9}', true, false, true, false, 2),
    ('dvd-video', 'DVD-Video', '{dvd5,dvd9}', false, false, true, false, 3),
    ('psp', 'Sony PlayStation Portable', '{dvd5,umd1,umd2}', false, false, true, false, 4),
    ('mcd', 'Sega Mega CD & Sega CD', '{cd}', true, false, true, false, 5),
    ('gc', 'Nintendo GameCube', '{dvd5gc}', false, false, false, false, 6),
    ('dc', 'Sega Dreamcast', '{cd,gdrom}', true, false, true, false, 7),
    ('wii', 'Nintendo Wii', '{dvd5wii,dvd9wii}', false, false, false, false, 8),
    ('ss', 'Sega Saturn', '{cd}', true, false, true, false, 9),
    ('3do', 'Panasonic 3DO Interactive Multiplayer', '{cd}', false, false, false, false, 10),
    ('pc', 'IBM PC compatible', '{cd,dvd5,dvd9,bd50}', false, true, true, false, 11),
    ('pce', 'NEC PC Engine CD & TurboGrafx CD', '{cd}', false, false, false, false, 12),
    ('cdtv', 'Commodore Amiga CDTV', '{cd}', true, false, true, false, 13),
    ('cd32', 'Commodore Amiga CD32', '{cd}', true, false, true, false, 14),
    ('acd', 'Commodore Amiga CD', '{cd}', true, false, true, false, 15),
    ('audio-cd', 'Audio CD', '{cd}', false, false, false, false, 16),
    ('qis', 'Bandai Playdia Quick Interactive System', '{cd}', true, false, true, false, 17),
    ('pippin', 'Bandai Pippin', '{cd}', false, false, false, false, 18),
    ('pc-98', 'NEC PC-98 series', '{cd}', true, false, true, false, 19),
    ('ps3', 'Sony PlayStation 3', '{cd,dvd5,dvd9,bd25,bd50}', false, false, true, false, 20),
    ('xbox', 'Microsoft Xbox', '{cd,dvd5,dvd9}', false, false, true, false, 21),
    ('xbox360', 'Microsoft Xbox 360', '{cd,dvd5,dvd9}', false, false, true, false, 22),
    ('mac', 'Apple Macintosh', '{cd,dvd5,dvd9}', false, true, true, false, 23),
    ('fmt', 'Fujitsu FM Towns series', '{cd}', true, false, true, false, 24),
    ('hs', 'Mattel HyperScan', '{cd}', true, false, true, false, 25),
    ('cdi', 'Philips CD-i', '{cd}', false, false, true, false, 26),
    ('vcd', 'Video CD', '{cd}', false, false, true, false, 27),
    ('naomi', 'Sega Naomi', '{gdrom}', true, false, true, false, 28),
    ('trf', 'Namco · Sega · Nintendo Triforce', '{gdrom}', true, false, true, false, 29),
    ('chihiro', 'Sega Chihiro', '{gdrom}', true, false, true, false, 30),
    ('pc-fx', 'NEC PC-FX & PC-FXGA', '{cd}', false, false, false, false, 31),
    ('vflash', 'VTech V.Flash & V.Smile Pro', '{cd}', false, false, true, false, 32),
    ('ngcd', 'Neo Geo CD', '{cd}', true, false, true, false, 33),
    ('bd-video', 'BD-Video', '{bd25,bd50}', false, false, true, false, 34),
    ('palm', 'Palm OS', '{cd}', false, false, true, false, 35),
    ('photo-cd', 'Photo CD', '{cd}', false, false, true, false, 36),
    ('lindbergh', 'Sega Lindbergh', '{dvd5}', false, false, false, false, 37),
    ('ps4', 'Sony PlayStation 4', '{bd25,bd50}', false, false, true, false, 38),
    ('pc-88', 'NEC PC-88 series', '{cd}', false, false, false, false, 39),
    ('enhanced-cd', 'Enhanced CD', '{cd}', false, false, true, false, 40),
    ('wiiu', 'Nintendo Wii U', '{bd25wiiu}', false, false, false, false, 41),
    ('xboxone', 'Microsoft Xbox One', '{bd25,bd50}', false, false, true, false, 42),
    ('psxgs', 'PlayStation GameShark Updates', '{cd}', false, false, false, false, 43),
    ('ksite', 'Tomy Kiss-Site', '{cd}', false, false, true, false, 44),
    ('gamewave', 'ZAPiT Games Game Wave Family Entertainment System', '{dvd5}', false, false, true, false, 45),
    ('quizard', 'TAB-Austria Quizard', '{cd}', false, false, true, false, 46),
    ('naomi2', 'Sega Naomi 2', '{gdrom}', true, false, true, false, 47),
    ('ns246', 'Namco System 246', '{cd,dvd5}', false, false, true, false, 48),
    ('ksgv', 'Konami System GV', '{cd}', true, false, true, false, 49),
    ('nuon', 'VM Labs NUON', '{dvd5}', false, false, true, false, 50),
    ('sre2', 'Sega RingEdge 2', '{dvd5,dvd9}', false, false, false, false, 51),
    ('kea', 'Konami e-Amusement', '{cd,dvd5}', true, false, true, false, 52),
    ('ite', 'Incredible Technologies Eagle', '{cd}', false, false, true, false, 53),
    ('kfb', 'Konami FireBeat', '{cd,dvd5}', true, false, true, false, 54),
    ('km2', 'Konami M2', '{cd}', false, false, false, false, 55),
    ('sre', 'Sega RingEdge', '{dvd5,dvd9}', false, false, false, false, 56),
    ('hvnxp', 'Hasbro VideoNow XP', '{cd}', false, false, false, false, 57),
    ('m2', 'Panasonic M2', '{cd}', false, false, false, false, 58),
    ('hvnc', 'Hasbro VideoNow Color', '{cd}', false, false, false, false, 59),
    ('hvnjr', 'Hasbro VideoNow Jr.', '{cd}', false, false, false, false, 60),
    ('navi21', 'Navisoft Naviken 2.1', '{cd}', true, false, false, false, 61),
    ('vis', 'Memorex Visual Information System', '{cd}', false, false, true, false, 62),
    ('ixl', 'Mattel Fisher-Price iXL', '{cd}', false, false, true, false, 63),
    ('ajcd', 'Atari Jaguar CD Interactive Multimedia System', '{cd}', false, false, false, false, 64),
    ('hvn', 'Hasbro VideoNow', '{cd}', false, false, false, false, 65),
    ('fpp', 'funworld Photo Play', '{cd}', false, false, false, false, 66),
    ('sp21', 'Sega Prologue 21 Multimedia Karaoke System', '{cd}', false, false, true, false, 67),
    ('arch', 'Acorn Archimedes', '{cd}', false, false, true, false, 68),
    ('ppc', 'Pocket PC', '{cd}', false, false, true, false, 69),
    ('hddvd-video', 'HD DVD-Video', '{hdvd15,hdvd30}', false, false, false, false, 70),
    ('x68k', 'Sharp X68000', '{cd}', false, false, false, false, 71),
    ('iktv', 'Tao iKTV', '{cd}', false, false, false, false, 72),
    ('ks573', 'Konami System 573', '{cd}', true, false, true, false, 73),
    ('xboxsx', 'Microsoft Xbox Series X', '{bd25,bd50}', false, false, true, false, 74),
    ('ps5', 'Sony PlayStation 5', '{bd66,bd100}', false, false, true, false, 75);

-- OIDC clients seed (for phpBB and MediaWiki)
INSERT INTO oauth_clients (client_id, client_secret, redirect_uri, name) VALUES
    ('phpbb-client', 'change-this-secret-phpbb', 'http://localhost:8080/forum/ucp.php?mode=login', 'phpBB Forum'),
    ('mediawiki-client', 'change-this-secret-mediawiki', 'http://localhost:8080/wiki/Special:PluggableAuthLogin', 'MediaWiki');
